apiVersion: aziot-edge.com/v1
kind: IotedgeBroker
metadata:
  name: edgy
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-failed
spec:
  frontend:  
    replicas: {{ .Values.broker.frontend.replicas }}
  backendChain:
    replicas: {{ .Values.broker.backend.replicas }}
    chainCount: {{ .Values.broker.backend.chainCount }}
  image:
    repository: "{{ .Values.broker.repository }}"
    tag: "{{ .Values.broker.tag }}"