{{- $fullName := include "dmqtt.fullname" . -}}
apiVersion: aziot-edge.com/v1
kind: IotedgeBroker
metadata:
 name: {{ $fullName }}-broker
spec:
 frontend:
   replicas: {{ .Values.broker.frontend.replicas }}
 backendChain:
   replicas: {{ .Values.broker.backend.replicas }}
   chainCount: {{ .Values.broker.backend.chainCount }}
 image:
   repository: "{{ .Values.broker.image.repository }}"
   tag: "{{ .Values.broker.image.tag }}"
