apiVersion: aziot-edge.com/v1
kind: IotedgeBroker
metadata:
 name: edgy
spec:
 frontend:
   replicas: 2
 backendChain:
   replicas: 1
   chainCount: 2
 image:
   repository: dmqttdemo.azurecr.io/dmqtt-broker
   tag: latest
