{{- $fullName := include "dmqtt.fullname" . -}}
apiVersion: aziot-edge.com/v1
kind: IotedgeBroker
metadata:
 name: {{ $fullName }}-broker
spec:
 frontend:
   replicas: {{- with .Values.broker.frontend.replicas }}
 backendChain:
   replicas: {{- with .Values.broker.backend.replicas }}
   chainCount: {{- with .Values.broker.backend.chainCount }}
 image:
   repository: "{{- with .Values.broker.image.repository }}"
   tag: "{{- with .Values.broker.image.tag }}"
   {{- end }}
