# Required cluster role to allow spire-agent to query k8s API server
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iotedge-spiffe-agent-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods","nodes","nodes/proxy"]
  verbs: ["get","list"]

---
# Binds above cluster role to spire-agent service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iotedge-spiffe-agent-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: iotedge-spiffe-agent
  namespace: default   
roleRef:
  kind: ClusterRole
  name: iotedge-spiffe-agent-cluster-role
  apiGroup: rbac.authorization.k8s.io